package thelm.textreplacer;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import net.minecraft.client.Minecraft;
import net.minecraft.client.resources.IReloadableResourceManager;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(
		modid = TextReplacer.MOD_ID,
		name = TextReplacer.NAME,
		version = TextReplacer.VERSION,
		clientSideOnly = true
		)
public class TextReplacer {

	public static final String MOD_ID = "textreplacer";
	public static final String NAME = "TextReplacer";
	public static final String VERSION = "1.12.2-1.0.0.0";
	public static final String DEPENDENCIES = "required-after:textevents";
	public static final Logger LOGGER = LogManager.getLogger("TextReplacer");
	public static ModMetadata metadata;

	@Mod.EventHandler
	public void firstMovement(FMLPreInitializationEvent event) {
		metadata = event.getModMetadata();
		metadata.autogenerated = false;
		metadata.version = VERSION;
		metadata.authorList.add("TheLMiffy1111");
		metadata.description = "A WIP mod that replaces certain vanilla text.";

		MinecraftForge.EVENT_BUS.register(EventHandler.INSTANCE);
		LoggingManager.register();
	}

	@Mod.EventHandler
	public void secondMovement(FMLInitializationEvent event) {

	}

	@Mod.EventHandler
	public void thirdMovement(FMLPostInitializationEvent event) {
		((IReloadableResourceManager)Minecraft.getMinecraft().getResourceManager()).registerReloadListener(EventHandler.INSTANCE);
	}
}
